---
name: Object-eBay
version: 0.0.3
author:
  - 'Michael Hendricks  <michael@ndrix.com>'
abstract: Object-oriented interface to the eBay API
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Std: 0.0.8
  Net::eBay: 0.28
  Scalar::Util: 1.02
build_requires:
  Test::More: 0
provides:
  Object::eBay:
    file: lib/Object/eBay.pm
    version: 0.0.3
  Object::eBay::Boolean:
    file: lib/Object/eBay/Boolean.pm
    version: 0.0.3
  Object::eBay::Currency:
    file: lib/Object/eBay/Currency.pm
    version: 0.0.3
  Object::eBay::Item:
    file: lib/Object/eBay/Item.pm
    version: 0.0.3
  Object::eBay::ListingDetails:
    file: lib/Object/eBay/ListingDetails.pm
    version: 0.0.3
  Object::eBay::SellingStatus:
    file: lib/Object/eBay/SellingStatus.pm
    version: 0.0.3
  Object::eBay::User:
    file: lib/Object/eBay/User.pm
    version: 0.0.3
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
